name: CodecFakeSourceTracing
channels:
  - pytorch
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - blas=1.0
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2025.2.25
  - certifi=2024.8.30
  - charset-normalizer=3.3.2
  - cuda-cudart=12.4.127
  - cuda-cudart_linux-64=12.4.127
  - cuda-cupti=12.4.127
  - cuda-libraries=12.4.1
  - cuda-nvrtc=12.4.127
  - cuda-nvtx=12.4.127
  - cuda-opencl=12.4.127
  - cuda-runtime=12.4.1
  - cuda-version=12.4
  - ffmpeg=4.3
  - filelock=3.13.1
  - freetype=2.13.3
  - gmp=6.3.0
  - gmpy2=2.1.2
  - gnutls=3.6.15
  - idna=3.7
  - intel-openmp=2023.1.0
  - jinja2=3.1.4
  - jpeg=9e
  - lame=3.100
  - lcms2=2.16
  - ld_impl_linux-64=2.40
  - lerc=4.0.0
  - libcublas=12.4.5.8
  - libcufft=11.2.1.3
  - libcufile=1.9.1.3
  - libcurand=10.3.5.147
  - libcusolver=11.6.1.9
  - libcusparse=12.3.1.170
  - libdeflate=1.22
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libiconv=1.16
  - libidn2=2.3.4
  - libjpeg-turbo=2.0.0
  - libnpp=12.2.5.30
  - libnvfatbin=12.4.127
  - libnvjitlink=12.4.127
  - libnvjpeg=12.3.1.117
  - libpng=1.6.39
  - libstdcxx-ng=11.2.0
  - libtasn1=4.19.0
  - libtiff=4.5.1
  - libunistring=0.9.10
  - libwebp-base=1.3.2
  - llvm-openmp=14.0.6
  - lz4-c=1.9.4
  - markupsafe=2.1.3
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.8
  - mkl_random=1.2.4
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - ncurses=6.4
  - nettle=3.7.3
  - networkx=3.1
  - ocl-icd=2.3.2
  - openh264=2.1.1
  - openjpeg=2.5.2
  - openssl=3.0.16
  - pillow=10.4.0
  - pip=24.2
  - pysocks=1.7.1
  - python=3.8.20
  - pytorch=2.4.1
  - pytorch-cuda=12.4
  - pytorch-mutex=1.0
  - pyyaml=6.0.2
  - readline=8.2
  - requests=2.32.3
  - setuptools=75.1.0
  - sqlite=3.45.3
  - sympy=1.13.3
  - tbb=2021.8.0
  - tk=8.6.14
  - torchaudio=2.4.1
  - torchtriton=3.0.0
  - torchvision=0.19.1
  - typing_extensions=4.11.0
  - urllib3=2.2.3
  - wheel=0.44.0
  - xz=5.6.4
  - yaml=0.2.5
  - zlib=1.2.13
  - zstd=1.5.6
  - pip:
      - antlr4-python3-runtime==4.9.3
      - audioread==3.0.1
      - bitarray==3.3.1
      - cffi==1.17.1
      - colorama==0.4.6
      - contourpy==1.1.1
      - cycler==0.12.1
      - decorator==5.2.1
      - fonttools==4.57.0
      - fsspec==2025.3.0
      - huggingface-hub==0.30.2
      - hydra==2.5
      - hydra-core==1.3.2
      - importlib-metadata==8.5.0
      - importlib-resources==6.4.5
      - joblib==1.4.2
      - kiwisolver==1.4.7
      - lazy-loader==0.4
      - librosa==0.11.0
      - llvmlite==0.41.1
      - lxml==5.4.0
      - matplotlib==3.7.5
      - msgpack==1.1.0
      - numba==0.58.1
      - numpy==1.23.5
      - omegaconf==2.3.0
      - packaging==25.0
      - platformdirs==4.3.6
      - pooch==1.8.2
      - portalocker==3.0.0
      - protobuf==5.29.4
      - pycparser==2.22
      - pyparsing==3.1.4
      - python-dateutil==2.9.0.post0
      - regex==2024.11.6
      - sacrebleu==2.5.1
      - safetensors==0.5.3
      - scikit-learn==1.3.2
      - scipy==1.10.1
      - six==1.17.0
      - soundfile==0.13.1
      - soxr==0.3.7
      - tabulate==0.9.0
      - tensorboardx==2.6.2.2
      - threadpoolctl==3.5.0
      - timm==1.0.15
      - tokenizers==0.20.3
      - tqdm==4.67.1
      - transformers==4.46.3
      - webrtcvad==2.0.10
      - zipp==3.20.2
